config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get '/about', to:'static#about', as: :about

	resources :bars
end  

app/models/bar.rb
class Bar < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
  	@bars = Bar.all
  end

  def show
  	@bar = Bar.find(params[:id])
  end

  def new
  	@bar = Bar.new
  end

  def create
  	@bar = Bar.new(bar_params)

  	if @bar.save
  		redirect_to bars_path
  	else
  		render :new
  	end
  end

  def edit
  	@bar = Bar.find(params[:id])
  end

  def update
  	@bar = Bar.find(params[:id])

  	if @bar.update_attributes(bar_params)
  		redirect_to bars_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@bar = Bar.find(params[:id])
  	@bar.destroy

  	redirect_to bars_path
  end

  private

  def bar_params
  	params.require(:bar).permit(:name, :happyhour, :specials, :location)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/bars/edit.html.erb
<h1> Edit Place </h1>
<%= form_for @bar do |b| %>
	<%= b.label :name %>
	<%= b.text_field :name %>

	<%= b.label :happyhour %>
	<%= b.text_field :happyhour %>

	<%= b.label :specials %>
	<%= b.text_area :specials %>

	<%= b.label :location %>
	<%= b.text_area :location %>

	<%= b.submit %>
<% end %>

app/views/bars/index.html.erb
<h1> BARS: </h1>
<%= link_to 'Add Bar', new_bar_path %>
<% @bars.each do |bar| %>
<address>
	<strong><%= bar.name %></strong><br>
	<%= bar.location %><br>
</address>
	<h3><%= bar.name %></h3>
	<p><%= bar.happyhour %></p>
	<p><%= bar.specials %></p>
	<p><%= bar.location %></p>
	<p><%= link_to 'Show bar', bar_path(bar.id) %></p>
	<p><%= link_to 'Edit Bar', edit_bar_path(bar.id) %></p>
	<p><%= link_to 'Delete Bar', bar, method: :delete %></p>
	
<% end %>


<!-- <address>
  <strong>Twitter, Inc.</strong><br>
  1355 Market Street, Suite 900<br>
  San Francisco, CA 94103<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890
</address> -->

app/views/bars/new.html.erb
<%= form_for @bar do |b| %>
	<%= b.label :name %>
	<%= b.text_field :name %>

	<%= b.label :happyhour %>
	<%= b.text_field :happyhour %>

	<%= b.label :specials %>
	<%= b.text_area :specials %>

	<%= b.label :location %>
	<%= b.text_area :location %>

	<%= b.submit %>
<% end %>

app/views/bars/show.html.erb
<h1>Happy Hour:</h1>
<h3><%= @bar.name %></h3>
<h4><%= @bar.happyhour %></h4>
<p><%= @bar.specials %></p>
<p><%= @bar.location %></p>
<%= link_to 'Back', bars_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand scroll" href="#intro">Twitter Bootstrap with Parallax scrolling</a>
			<ul class="nav">
				<li class="active"><a class="scroll" href="#intro">Home</a></li>
        <li><a class="scroll" href="#features">Features</a></li>
        <li><a class="scroll" href="#about">About</a></li>
      </ul>
		</div>
	</div>

			<div class="navbar-header">
				<a class="brand scroll" href="#intro">Twitter Bootstrap with Parallax scrolling</a>
        <ul class="nav">
          <li class="active"><a class="scroll" href="#intro">Home</a></li>
          <li><a class="scroll" href="#features">Features</a></li>
          <li><a class="scroll" href="#about">About</a></li>
        </ul>    
				<a class="navbar-brand" href="/">
					<i class="icon ion-beer"></i>
				</a>
			</div>
	<div class="form-group">
		<input type="text" class="form-control" placeholder="Search (for happy hour)">
	</div>
	<button class="btn btn-default" type="submit">
		<b>Submit</b>
	</button>  
</nav>

<%= link_to 'Home', root_path %>
	<%= link_to 'About', about_path %>
	<%= link_to 'Bars', bars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
  	<title>Happy Hour Specials</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" media="screen">
  	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">
	</head>
	<body>
		<%= render 'layouts/navbar' %>

		<%= yield %>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
		<script src="js/skrollr.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/_main.js"></script>	
		<script src="js/jquery-1.8.2.min.js"></script>
    <script src="js/jquery.scrollTo-1.4.3.1-min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/script.js"></script>
	</body>
</html>